# Generated by Django 4.2.1 on 2025-11-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0002_women_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="women",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
