# Generated by Django 4.2.1 on 2025-11-18 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0004_alter_women_managers_alter_women_is_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="women",
            options={"ordering": ["-time_create"]},
        ),
        migrations.AlterModelManagers(
            name="women",
            managers=[],
        ),
        migrations.AddIndex(
            model_name="women",
            index=models.Index(
                fields=["-time_create"], name="women_women_time_cr_9f33c2_idx"
            ),
        ),
        migrations.AddField(
            model_name="women",
            name="cat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="women.category",
            ),
        ),
    ]
