# Generated by Django 4.2.1 on 2025-11-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("women", "0005_category_alter_women_options_alter_women_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="women",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="women.category"
            ),
        ),
    ]
